apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "maildev.fullname" . }}
  labels:
    {{- include "maildev.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "maildev.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "maildev.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "maildev.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- if .Values.command }}
          command: {{- toYaml .Values.command | nindent 12 }}
          {{- end }}
          {{- if .Values.args }}
          args: {{- toYaml .Values.args | nindent 12 }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - name: smtp-port
            containerPort: {{ .Values.ports.smtp }}
            protocol: TCP
          - name: web-port
            containerPort: {{ .Values.ports.web }}
            protocol: TCP
          env:
          - name: MAILDEV_SMTP_PORT
            value: "{{ .Values.ports.smtp }}"
          - name: MAILDEV_WEB_PORT
            value: "{{ .Values.ports.web }}"
          {{- range $name, $value := .Values.env }}
          - name: {{ $name }}
            value: {{ $value }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.ports.web }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.ports.web }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: auto-relay-rules
            mountPath: /etc/maildev
            subPath: auto-relay-rules.json
      volumes:
      - name: auto-relay-rules
        configMap:
          name: {{ include "maildev.fullname" . }}-relay-rules
          items:
          - key: auto-relay-rules.json
            path: auto-relay-rules.json
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
