{{- if .Values.ports.smtp }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "maildev.fullname" . }}
  labels:
    {{- include "maildev.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: smtp
      port: {{ .Values.ports.smtp }}
      protocol: TCP
      targetPort: {{ .Values.ports.smtp }}
    - name: web
      port: {{ .Values.ports.web }}
      protocol: TCP
      targetPort: {{ .Values.ports.web }}
  selector:
    {{- include "maildev.selectorLabels" . | nindent 4 }}
{{- end }}
